language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
before_install:
  - pip install git+git://srobo.org/comp/ranker.git
  - pip install git+git://srobo.org/comp/srcomp.git
  - pip install ruamel.yaml
install: python setup.py install
script: ./run-tests
